# zsh
[terminal.shell]
program = "/bin/zsh"
#program = "/usr/bin/tmux"
#args = ["a"]

[window]
opacity = 1.0
blur = true
title = "Gentooey <3"
decorations = "Full"

[scrolling]
history = 100000

[font.normal]
family = "MesloLGS NF"

[colors.primary]
background = "#000000"

[env]
TERM = "alacritty"

[colors.bright]
black = "#000000"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#000000"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[font]
size = 12.5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 24

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
